name: Format

on:
  pull_request:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: rustfmt
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - run: rustup update stable && rustup default stable
      - run: rustup component add rustfmt
      - run: cargo fmt
      - name: Auto-commit formatting fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto cargo fmt"
